version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    rebase-strategy: "auto"

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
