[package]
name = "dotfile-manager"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dman"
path = "src/cli/main.rs"

[[bin]]
name = "dman-gui"
path = "src/gui/main.rs"

[dependencies]
clap = "4"
git2 = "0"
serde = {version = "1", features = ["derive"]}
toml = "0"
