name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev -y
      # libpango1.0-dev libgraphene-1.0-dev libadwaita-1-dev
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Lint
        run: |
          cargo fmt -v --check
          cargo clippy --features gui -- -D warnings

      - name: Test
        run: |
          cargo check --features gui
          cargo test --all --features gui

      - name: Build
        run: cargo build --release --features gui

      - name: NPM
        run: npm run build
